"use client";

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

function Section({ title, children }: SectionProps) {
  return (
    <div className="mb-10">
      <h2 className="text-2xl font-semibold text-purple-500 mb-3">
        {title}
      </h2>
      <div className="text-gray-700 leading-relaxed">{children}</div>
    </div>
  );
}

export default function TermsConditions() {
  return (
    <div className="min-h-screen bg-gray-100 py-16 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-xl p-10 border border-gray-200">

        <h1 className="text-4xl font-bold text-purple-600 mb-4">
          Terms & Conditions
        </h1>

        <p className="text-gray-500 text-sm mb-10">
          <strong>Effective Date:</strong> 02-04-2025
        </p>

        <p className="text-gray-700 leading-relaxed mb-6">
          This document is an electronic record in terms of the Information Technology
          Act, 2000 and rules thereunder. This electronic record is generated by a
          computer system and does not require any physical or digital signatures.
        </p>

        <p className="text-gray-700 leading-relaxed mb-6">
          This document is published in accordance with Rule 3 (1) of the Information
          Technology (Intermediary Guidelines) Rules, 2011, that require publishing the
          rules and regulations, privacy policy, and Terms of Use for access or usage
          of the website <strong>vishnucvs.in</strong> (“Website”).
        </p>

        <p className="text-gray-700 leading-relaxed mb-8">
          The Website is owned by <strong>Vasavi Marketing</strong>, having its
          registered office at Kurnool(D), Sirvella (M), Yerraguntla (V), Main Street,
          Murali Book Stores Opposite, 518510 (hereinafter referred to as “we”, “us”,
          or “our”).
        </p>

        <Section title="Agreement to Terms">
          <p>
            By accessing, browsing, or using this Website and its services, you agree
            to be bound by these Terms of Use and all applicable policies. If you do
            not agree, please do not use the Platform.
          </p>
        </Section>

        <Section title="1. Accuracy of Information">
          <p>
            You agree to provide true, accurate, and complete information during
            registration and are responsible for all activities carried out through
            your account.
          </p>
        </Section>

        <Section title="2. No Warranty">
          <p>
            The information and services on this Platform are provided “as is”.
            We do not guarantee accuracy, completeness, or suitability for any
            particular purpose and exclude liability to the fullest extent
            permitted by law.
          </p>
        </Section>

        <Section title="3. Use at Your Own Risk">
          <p>
            Your use of the Platform and Services is entirely at your own risk.
            You are responsible for ensuring that the Services meet your requirements.
          </p>
        </Section>

        <Section title="4. Intellectual Property">
          <p>
            All content including design, layout, graphics, and text is proprietary
            to Vasavi Marketing. You have no rights to copy, reproduce, or use
            the content without prior written permission.
          </p>
        </Section>

        <Section title="5. Unauthorized Use">
          <p>
            Unauthorized use of the Platform may result in legal action under
            applicable laws and these Terms.
          </p>
        </Section>

        <Section title="6. Service Charges">
          <p>
            You agree to pay all applicable charges for availing Services from
            the Platform.
          </p>
        </Section>

        <Section title="7. Lawful Use">
          <p>
            You shall not use the Platform for any unlawful, illegal, or prohibited
            purpose under Indian law.
          </p>
        </Section>

        <Section title="8. Third-Party Links">
          <p>
            The Platform may contain links to third-party websites. We are not
            responsible for the content or policies of such websites.
          </p>
        </Section>

        <Section title="9. Legally Binding Contract">
          <p>
            By initiating a transaction on the Platform, you enter into a legally
            binding contract with Vasavi Marketing.
          </p>
        </Section>

        <Section title="10. Indemnity">
          <p>
            You agree to indemnify and hold harmless Vasavi Marketing from any claims,
            losses, penalties, or legal expenses arising from your violation of these
            Terms or applicable laws.
          </p>
        </Section>

        <Section title="11. Limitation of Liability">
          <p>
            Our liability shall not exceed the amount paid by you for the Services
            or Rs. 100, whichever is less. We shall not be liable for indirect,
            incidental, or consequential damages.
          </p>
        </Section>

        <Section title="12. Force Majeure">
          <p>
            We shall not be liable for failure or delay in performance due to events
            beyond our reasonable control.
          </p>
        </Section>

        <Section title="13. Governing Law & Jurisdiction">
          <p>
            These Terms shall be governed by the laws of India. All disputes shall be
            subject to the exclusive jurisdiction of the courts in Andhra Pradesh.
          </p>
        </Section>

        <Section title="14. Contact Information">
          <p>
            🏢 Address: Kurnool(D), Sirvella (M), Yerraguntla (V), Main Street,
            Murali Book Stores Opposite, 518510
          </p>
        </Section>

        <p className="text-sm text-gray-500">
          Continued use of this Website indicates acceptance of these Terms & Conditions.
        </p>

      </div>
    </div>
  );
}
